# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_calorie_title', models.CharField(max_length=250)),
                ('exercise_calorie_burn', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.CharField(max_length=250)),
                ('food_title', models.CharField(max_length=250)),
                ('name_title', models.CharField(max_length=250)),
                ('calories_title', models.CharField(max_length=250)),
                ('fat_title', models.CharField(max_length=250)),
                ('protein_title', models.CharField(max_length=250)),
                ('carbs_title', models.CharField(max_length=250)),
                ('fiber_title', models.CharField(max_length=250)),
                ('type_title', models.CharField(max_length=250)),
                ('calcium_title', models.CharField(max_length=250)),
                ('cholestrol_title', models.CharField(max_length=250)),
                ('iron_title', models.CharField(max_length=250)),
                ('magnesium_title', models.CharField(max_length=250)),
                ('sodium_title', models.CharField(max_length=250)),
                ('phosphorous_title', models.CharField(max_length=250)),
                ('potassium_title', models.CharField(max_length=250)),
                ('zinc_title', models.CharField(max_length=250)),
                ('niacin_title', models.CharField(max_length=250)),
                ('vitamina_title', models.CharField(max_length=250)),
                ('vitaminb6_title', models.CharField(max_length=250)),
                ('vitaminc_title', models.CharField(max_length=250)),
            ],
        ),
    ]
